version: "3"
services:
  latex:
    build: .
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ./.latexmkrc:/root/.latexmkrc
      - ~/.gitconfig:/root/.gitconfig
    environment:
      SHELL: "/bin/bash"
